from contextlib import AbstractContextManager
from datetime import datetime
from decimal import Decimal
from typing import Protocol, Sequence

from libracommerce.domain.catalog import (
    CatalogItem,
    CatalogItemType,
    ItemCode,
    ItemCodeType,
    ItemPrice,
    ItemVariant,
    PriceList,
)
from libracommerce.domain.entities import Party
from libracommerce.domain.inventory import Location, StockMovement
from libracommerce.domain.purchasing import PurchaseOrder, PurchaseReceipt
from libracommerce.domain.sales import Sale


class CommerceRepository(Protocol):
    def save_party(self, party: Party) -> Party: ...
    def save_catalog_item(self, item: CatalogItem) -> CatalogItem: ...
    def get_catalog_item(self, item_id: int) -> CatalogItem | None: ...
    def list_catalog_items(
        self,
        *,
        active_only: bool = False,
        sellable_only: bool = False,
        item_type: CatalogItemType | None = None,
        search: str = "",
    ) -> Sequence[CatalogItem]: ...
    def save_item_code(self, item_code: ItemCode) -> ItemCode: ...
    def list_item_codes(self, item_id: int) -> Sequence[ItemCode]: ...
    def find_item_by_code(
        self, code: str, *, code_type: ItemCodeType | None = None
    ) -> CatalogItem | None: ...
    def get_setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def save_item_variant(self, variant: ItemVariant) -> ItemVariant: ...
    def get_item_variant(self, variant_id: int) -> ItemVariant | None: ...
    def list_item_variants(self, item_id: int) -> Sequence[ItemVariant]: ...
    def save_price_list(self, price_list: PriceList) -> PriceList: ...
    def get_price_list(self, price_list_id: int) -> PriceList | None: ...
    def save_item_price(self, item_price: ItemPrice) -> ItemPrice: ...
    def list_item_prices(self, item_id: int) -> Sequence[ItemPrice]: ...
    def resolve_price(
        self,
        item_id: int,
        *,
        price_list_id: int | None = None,
        quantity: Decimal = Decimal("1"),
        at: datetime | None = None,
        branch_id: int | None = None,
    ) -> Decimal | None: ...
    def save_location(self, location: Location) -> Location: ...
    def get_location(self, location_id: int) -> Location | None: ...
    def list_locations(self, *, active_only: bool = False) -> Sequence[Location]: ...
    def append_stock_movement(self, movement: StockMovement) -> StockMovement: ...
    #: Proyeccion de `stock_movements`. Estaba solo en el adaptador SQLite; se
    #: declara aca desde que un caso de uso la necesita para decidir (la
    #: guarda de disponibilidad de `usecases/inventory.py`).
    def current_stock(
        self, item_id: int, location_id: int, *, variant_id: int | None = None
    ) -> Decimal: ...
    #: Agrupa varias escrituras en un solo commit, con rollback ante error.
    #: Sin esto una operacion de dos movimientos puede quedar por la mitad.
    def transaction(self) -> AbstractContextManager["CommerceRepository"]: ...
    def save_sale(self, sale: Sale) -> Sale: ...
    def list_stock_movements(self, item_id: int, location_id: int) -> Sequence[StockMovement]: ...
    def list_stock_movements_by_source(
        self, source_type: str, source_id: int
    ) -> Sequence[StockMovement]: ...
    def save_purchase_order(self, order: PurchaseOrder) -> PurchaseOrder: ...
    def get_purchase_order(self, order_id: int) -> PurchaseOrder | None: ...
    def list_purchase_orders(self) -> Sequence[PurchaseOrder]: ...
    def save_purchase_receipt(self, receipt: PurchaseReceipt) -> PurchaseReceipt: ...
    def get_purchase_receipt(self, receipt_id: int) -> PurchaseReceipt | None: ...
    def list_purchase_receipts(self) -> Sequence[PurchaseReceipt]: ...
