from datetime import datetime
from decimal import Decimal
from typing import Protocol, Sequence

from libracommerce.domain.catalog import CatalogItem, ItemCode, ItemPrice, PriceList
from libracommerce.domain.entities import Party
from libracommerce.domain.inventory import Location, StockMovement
from libracommerce.domain.purchasing import PurchaseOrder, PurchaseReceipt
from libracommerce.domain.sales import Sale


class CommerceRepository(Protocol):
    def save_party(self, party: Party) -> Party: ...
    def save_catalog_item(self, item: CatalogItem) -> CatalogItem: ...
    def get_catalog_item(self, item_id: int) -> CatalogItem | None: ...
    def save_item_code(self, item_code: ItemCode) -> ItemCode: ...
    def list_item_codes(self, item_id: int) -> Sequence[ItemCode]: ...
    def find_item_by_code(self, code: str) -> CatalogItem | None: ...
    def save_price_list(self, price_list: PriceList) -> PriceList: ...
    def get_price_list(self, price_list_id: int) -> PriceList | None: ...
    def save_item_price(self, item_price: ItemPrice) -> ItemPrice: ...
    def list_item_prices(self, item_id: int) -> Sequence[ItemPrice]: ...
    def resolve_price(
        self,
        item_id: int,
        *,
        price_list_id: int | None = None,
        quantity: Decimal = Decimal("1"),
        at: datetime | None = None,
        branch_id: int | None = None,
    ) -> Decimal | None: ...
    def save_location(self, location: Location) -> Location: ...
    def append_stock_movement(self, movement: StockMovement) -> StockMovement: ...
    def save_sale(self, sale: Sale) -> Sale: ...
    def list_stock_movements(self, item_id: int, location_id: int) -> Sequence[StockMovement]: ...
    def save_purchase_order(self, order: PurchaseOrder) -> PurchaseOrder: ...
    def get_purchase_order(self, order_id: int) -> PurchaseOrder | None: ...
    def save_purchase_receipt(self, receipt: PurchaseReceipt) -> PurchaseReceipt: ...
