from typing import Protocol, Sequence

from libracommerce.domain.catalog import CatalogItem
from libracommerce.domain.entities import Party
from libracommerce.domain.inventory import Location, StockMovement
from libracommerce.domain.purchasing import PurchaseOrder, PurchaseReceipt
from libracommerce.domain.sales import Sale


class CommerceRepository(Protocol):
    def save_party(self, party: Party) -> Party: ...
    def save_catalog_item(self, item: CatalogItem) -> CatalogItem: ...
    def get_catalog_item(self, item_id: int) -> CatalogItem | None: ...
    def save_location(self, location: Location) -> Location: ...
    def append_stock_movement(self, movement: StockMovement) -> StockMovement: ...
    def save_sale(self, sale: Sale) -> Sale: ...
    def list_stock_movements(self, item_id: int, location_id: int) -> Sequence[StockMovement]: ...
    def save_purchase_order(self, order: PurchaseOrder) -> PurchaseOrder: ...
    def get_purchase_order(self, order_id: int) -> PurchaseOrder | None: ...
    def save_purchase_receipt(self, receipt: PurchaseReceipt) -> PurchaseReceipt: ...
